# Generated by Django 4.1 on 2022-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily',
            name='first_meet',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='other',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='univ',
        ),
        migrations.RemoveField(
            model_name='daily',
            name='wanna_do',
        ),
        migrations.AddField(
            model_name='daily',
            name='future_work',
            field=models.TextField(default='tmp'),
        ),
        migrations.AddField(
            model_name='daily',
            name='hobby',
            field=models.TextField(default='tmp'),
        ),
        migrations.AddField(
            model_name='daily',
            name='others',
            field=models.TextField(default='tmp'),
        ),
        migrations.AddField(
            model_name='daily',
            name='research',
            field=models.TextField(default='tmp'),
        ),
        migrations.AlterField(
            model_name='daily',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='evaluation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='daily',
            name='study',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
